### ISSUE TITLE
Export list of users who have Push Verify enabled? 

### ISSUE THREAD

**Issue by jgq85** [gabrielsroka/gabrielsroka.github.io#10]
Is there a way to view/export only users who have Okta Verify push notification enabled? 
The purpose would be for data gathering/reporting purposes as well as bulk MFA Resets for only those users.

**Comment by jgq85** [comment]
I was able to loop through users and use Get-OktaFactor

**Comment by gabrielsroka** [comment]
Hi @jgq85 
was this with PowerShell or rockstar? is there still an issue? or should we close this?

**Comment by gabrielsroka** [comment]
I'm going to close this. Please reopen if you need to.
