### ISSUE TITLE
New admin dashboard

### ISSUE THREAD

**Issue by erickufrin** [gabrielsroka/gabrielsroka.github.io#11]
The new admin dashboard is a left-side column... Shrinking the rockstar widget entirely is the only way to see all of the left-side column.

I dont know what would be best for all... but it could be ideal if the rockstar widget would dynamically position itself to the right of the column.

**Comment by gabrielsroka** [comment]
Hi @erickufrin,

I'm working on a fix. In the interim, you can use the minimize button `_` or the close `X` on the upper right hand side of the rockstar window.

![image](https://user-images.githubusercontent.com/14354736/95002191-22a61b80-0586-11eb-9906-810bcf76dbdf.png)

**Comment by gabrielsroka** [comment]
I'm going to close this. Please reopen if you need to.
