### ISSUE TITLE
New Okta admin dashboard hamburger menu is blocked by Rockstar widget

### ISSUE THREAD

**Issue by syoung-quizlet** [gabrielsroka/gabrielsroka.github.io#12]
Howdy!  Okta released their preview of the new admin dashboard.  The Rockstar widget covers the new hamburger menu.

![image](https://user-images.githubusercontent.com/43591190/107680325-8b975180-6c52-11eb-9f5f-fb5c9a985104.png)

**Comment by syoung-quizlet** [comment]
![image](https://user-images.githubusercontent.com/43591190/107680370-9eaa2180-6c52-11eb-9b91-e716148b8eb4.png)

**Comment by syoung-quizlet** [comment]
Wider screen view...
![image](https://user-images.githubusercontent.com/43591190/107680400-aa95e380-6c52-11eb-9664-c4904ee3151d.png)

**Comment by gabrielsroka** [comment]
you can minimize it using the `_` button. i'm working on a better fix

**Comment by sdamiano-nw** [comment]
I would love to see Rockstar move to the bottom left of the screen to be less intrusive.

**Comment by dregier** [comment]
It would be great if we could move Rockstar to one of the other corners of the screen.

**Comment by JasonBuckner** [comment]
rockstar version 0.20 looks to have added a means to shift the popup to the upper righthand corner (by clicking the "⇄" icon), where it remains in subsequent browser sessions! Very nice.
![CaptureA](https://user-images.githubusercontent.com/19961846/130476927-0c821ef8-d440-4e0d-8ae0-a4833e31dbf9.JPG)
