### ISSUE TITLE
CSV Export for Administrator List Mistakenly Attributing Limited Admin to All

### ISSUE THREAD

**Issue by Mrorya** [gabrielsroka/gabrielsroka.github.io#13]
Hi,

Using Chrome 89.0.4389.82 and the latest version of Rockstar, it appears that running the csv export on the administrator list page is mistakenly showing (all) for all admins with limited group roles (such as Group Membership Admin or Group Admin) - it seems that for _all_ of these limited admins - the Roles column is showing the Role Membership: (all) for these admins despite them only having limited access/limited admin roles.

**Comment by Mrorya** [comment]
If it helps, I'm also on the new admin experience

**Comment by gabrielsroka** [comment]
That report was written before Okta had a built-in report, and hasn't been maintained. I just tested it, and it worked fine for me. Do you "Add Admin" or "Add Admin Group" ?

Please use the built-in report.

**Comment by Mrorya** [comment]
I didn't actually realize this was built in now, thanks @gabrielsroka !
