### ISSUE TITLE
Pull Token Names List with Associated Domain

### ISSUE THREAD

**Issue by hortonjl** [gabrielsroka/gabrielsroka.github.io#15]
Is it possible to pull a list of AD Agent token names with the associated domain?

**Comment by gabrielsroka** [comment]
hi @hortonjl 

are you asking about rockstar? PowerShell? some other code?

what's a token name? i'm afraid i don't understand your question...

**Comment by hortonjl** [comment]
In Okta when I look at API Tokens, I can select to see the AD Agent Tokens, the list is the server names that are linked to the domain the server is in. In Rokstar on the page, I only have API Explorer, and don’t see a call to look at the tokens to export the names.

***@***.***D73A95.53B7C6D0]

***@***.***D73A95.950E27F0]


***@***.***D73A95.20F34170]Jim Horton
Information Protection Advisor
Cigna Identity Access Management
Authentication Team
Phone: 407-872-9824
Webex: https://esrx.webex.com/join/jhorton2

OOO 5/3/2021 – 5/10/2021



Confidential, unpublished property of Cigna. Do not duplicate or distribute.
Use and distribution limited solely to authorized personnel. Copyright 2020 Cigna

From: Gabriel Sroka ***@***.***>
Sent: Monday, April 26, 2021 11:44 AM
To: gabrielsroka/gabrielsroka.github.io ***@***.***>
Cc: Horton, James (ORL) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [gabrielsroka/gabrielsroka.github.io] Pull Token Names List with Associated Domain (#15)


hi @hortonjl<https://urldefense.com/v3/__https:/github.com/hortonjl__;!!GFE8dS6aclb0h1nkhPf9!rKkK3YE4RXAE8cEyP0_icaut3bwNYLTO0u-gyoc3mCs7adUjyQLlrrcIBHf2wGFtl0moB1k$>

are you asking about rockstar? PowerShell? some other code?

what's a token name? i'm afraid i don't understand your question...

**Comment by gabrielsroka** [comment]
It looks like the API for that is private:
`/api/internal/tokens?expand=user`

rockstar typically doesn't call private APIs, but you can do so yourself, eg using rockstar's API Explorer

**Comment by gabrielsroka** [comment]
Another option might be to go to Settings > Downloads, then on the right side, there's Download CSV button.

**Comment by gabrielsroka** [comment]
hi @hortonjl 

does this help? i'm going to close this for now. If you have more questions, please reopen it.

Thanks.

**Comment by hortonjl** [comment]
Big help, thanks.




***@***.***D73CFF.3728D970]Jim Horton
Information Protection Advisor
Cigna Identity Access Management
Authentication Team
Phone: 407-872-9824
Webex: https://esrx.webex.com/join/jhorton2

OOO 5/3/2021 – 5/10/2021



Confidential, unpublished property of Cigna. Do not duplicate or distribute.
Use and distribution limited solely to authorized personnel. Copyright 2020 Cigna

From: Gabriel Sroka ***@***.***>
Sent: Thursday, April 29, 2021 1:42 PM
To: gabrielsroka/gabrielsroka.github.io ***@***.***>
Cc: Horton, James (ORL) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [gabrielsroka/gabrielsroka.github.io] Pull Token Names List with Associated Domain (#15)


hi @hortonjl<https://urldefense.com/v3/__https:/github.com/hortonjl__;!!GFE8dS6aclb0h1nkhPf9!rSghBlyVJX92WaMxjVdegZMz0TEGArD4qXbkBMhbSglblL595I6DD5OoaloSrunAccZ_MHQ$>

does this help? i'm going to close this for now. If you have more questions, please reopen it.

Thanks.
