### ISSUE TITLE
Export App Users - Missing firstName and lastName

### ISSUE THREAD

**Issue by DCrawfordNHS** [gabrielsroka/gabrielsroka.github.io#18]
Hi Gabriel, Ive just used the "export app users" function in Rockstar (Chrome Ext) to export a list of app users (57000+)
The resulting report contains all "id" "userName" "scope" and "syncState" values however is missing firstName and lastName values.
I can confirm all of our user profiles contain this information.

**Comment by gabrielsroka** [comment]
@DCrawfordNHS it worked for me. 

Are you able to verify that the app user itself has a first/last name? (ie, not the user, but the app user). maybe using rockstar's API Explorer or Postman.

1. in Okta Admin, go to the app
2. from rockstar, click API Explorer
3. enter or select `/api/v1/apps/${appId}/users`, click Send
4. scroll right and view the users

![image](https://user-images.githubusercontent.com/14354736/120007146-6d99f680-bf8e-11eb-9bc1-5e5ba7d48e02.png)

**Comment by DCrawfordNHS** [comment]
Hi Gabriel, there is values for the following:
profile.given_name, profile.name and profile.family_name which all have values

**Comment by gabrielsroka** [comment]
but rockstar only exports firstName and lastName, not given_name and name and family_name

**Comment by DCrawfordNHS** [comment]
Hi Gabriel, thanks for looking into it, I was assuming they were feed from profile.lastName and profile.firstName in the user profiles which we have populated. I apologise for wasting your time. I would also like to thank you for a great tool you have created for OKTA, really appreciate your efforts and making this available to us.

**Comment by DCrawfordNHS** [comment]
Forgot to mention Gabriel, in the report you asked me to run I dont have firstName and lastName field.

**Comment by gabrielsroka** [comment]
You should be able to get what you need from the Okta API, eg using PowerShell (see below) or other languages such as Python.

https://github.com/gabrielsroka/OktaAPI.psm1/blob/master/CallOktaAPI.ps1#L59-L72

**Comment by DCrawfordNHS** [comment]
No probs Gabriel, sorted last Friday with Powershell.
