### ISSUE TITLE
Update JQuery in Rockstar Extension

### ISSUE THREAD

**Issue by lumnikemel** [gabrielsroka/gabrielsroka.github.io#19]
JQuery v1.12.4 is showing vulnerabilities. Please update extension to the latest JQuery.

We would like to use this extension to support our company, but we have a security policy that prevents installing extensions with known vulnerabilities.

**Vulnerability Sources**
- https://crxcavator.io/report/chjepkekmhealpjipcggnfepkkfeimbd?platform=Chrome
- https://snyk.io/test/npm/jquery/1.12.4

**Comment by gabrielsroka** [comment]
it was patched in May
https://github.com/gabrielsroka/gabrielsroka.github.io/commit/61c687965d096c45c7847dd740c43775ef3a416c

**Comment by lumnikemel** [comment]
It still shows up as vulnerable in CRXcavator's scan. There are more vulns between that version and current. Is there a reason it can't be upgraded?

**Comment by gabrielsroka** [comment]
that sounds like a CRXCavator bug, not mine.

this is the same version of jQuery that Okta uses.

if you'd like to fork the repo and upgrade it, please go ahead.
