### ISSUE TITLE
Error: Not found: Resource not found: {redacted} (AppLink)

### ISSUE THREAD

**Issue by jboyle-ld** [gabrielsroka/gabrielsroka.github.io#22]
Hello,
I'm receiving the following error when attempting to "export apps" using Rockstar:

"Error: Not found: Resource not found: {redacted} (AppLink)"

I have not been able to find the AppLink ID specified, either in the page source of the Applications page in the Okta admin UI, or when listing all Apps via the API.

GET {{url}}/api/v1/apps, does not return any errors.

If you can help track down this issue I would appreciate it.

Best,
J

**Comment by jboyle-ld** [comment]
Will do, thanks!

**Comment by jboyle-ld** [comment]
Okta support is still puzzling over our particular issue which appears to be specific to our tenant. In the interim, your solution does work to provide the results we need. Thanks for the recommendation!

**Comment by gabrielsroka** [comment]
@jboyle-ld 

any update on this? 

i can close this, and you can reopen it if it's still an issue...

**Comment by jboyle-ld** [comment]
Hey Gabriel,
Just solved the issue right now, there was a corrupt application configuration in our environment that was finally identified by Okta engineering, deleting it resolved the error. I'll close this issue out, thanks again for your help.
Best
J

**Comment by gabrielsroka** [comment]
I'm glad it worked. Can you provide any info (w/o details), on how they found/deleted it? They just looked in the log? It was an inactive app, right?

**Comment by jboyle-ld** [comment]
Yep, it was an inactive app. The api call was returning an error that contained an app link id and it looks like they were able to correlate that app link id (al.strLinkID) with an app instance name (ai.instance) by running a sql query. Once they were able to provide the name of the app, I was able to delete it manually from the admin console (we had several dozen inactive apps so it wasn't clear which was the culprit without that info). 

It's also worth noting that the app instance was clearly corrupted, the tabs weren't rendering properly and actions like clicking on the assignments tab even threw an embedded 404 error before the page froze completely, but clicking on "Delete" worked and then I was able to make the same api call without issue.
