### ISSUE TITLE
[Feature Request] Enhance User Management

### ISSUE THREAD

**Issue by macf0x** [gabrielsroka/gabrielsroka.github.io#24]
Firstly, what a great extension. Awesome work.

Would it be possible to add a feature to delete users, based on some criteria?

Criteria could be suspended or deactivated.

ie. In people explorer ->suspended /deactivated -> (add a button) delete

**Comment by DCrawfordNHS** [comment]
Hi macf0x,

Depending on your criteria this can be achieved via Workflows / Automation.

**Comment by macf0x** [comment]
True, Workflows and Automation do cover a part of this, but no all use cases.

A casual look through the Okta ideas / feature requests, will reveal being able to delete users in a bulk fashion, either by criteria or manual bulk selection, has remain ignored. Presumably for philosophical reasons.

In our organisation we have several 100 Okta Tenants. Admin is distributed and each has a unique AD/LDAP env.  Your extension tool in invaluable to these admins, but one area is adhoc bulk delete, that currently they can only perform per user.

**Comment by gabrielsroka** [comment]
rockstar doesn't really make changes.

here's a quick PowerShell script that uses my PowerShell module. it's only 15 lines

https://github.com/gabrielsroka/OktaAPI.psm1/blob/master/CallOktaAPI.ps1#L468-L482

@DCrawfordNHS , i'm not sure who you are, but thanks for your reply.

**Comment by gabrielsroka** [comment]
using the Official Python SDK:

https://github.com/okta/okta-sdk-python#pagination - pass it in a filter
https://github.com/okta/okta-sdk-python#remove-a-user

**Comment by macf0x** [comment]
We already use the PS modules, but it requires API keys, which expire. Great for regular automation, but not so much adhoc tasks. It's a shame it's not possible to use OAuth with those modules.

**Comment by gabrielsroka** [comment]
The API keys expire if you don't use them for 30 days. Just have a job (or a calendar reminder) to renew them every 30 days.

> OAuth
Someone would have to add that functionality. The PS modules were written before the Okta API supported OAuth.

Here's a Python example:
https://github.com/gabrielsroka/okta_api/blob/master/delete_users.py

**Comment by macf0x** [comment]
Expiry is the exact issue we're trying to get around, which lead us to this feature request.  But thanks for the info.

**Comment by gabrielsroka** [comment]
a little JavaScript you can run in browser, just like rockstar, it doesn't need an API token. it doesn't paginate or observe rate limits -- exercise is left to the reader.

```javascript
(async function () {
    const users = await $.getJSON('/api/v1/users?filter=status eq "DEPROVISIONED"'); // DEPROVISIONED, SUSPENDED, etc.
    for (const u of users) {
        console.log(u.profile.login, u.status);
        if (u.status != 'DEPROVISIONED') {
            await $.ajax(`/api/v1/users/${u.id}`, {method: 'delete'}); // Must delete it twice.
        }
        await $.ajax(`/api/v1/users/${u.id}`, {method: 'delete'});
    }
})();
```

see also https://gabrielsroka.github.io/APIExplorer/

**Comment by macf0x** [comment]
Cheers. That might just do the trick.

Thanks for providing this.

**Comment by gabrielsroka** [comment]
this version paginates, but it doesn't observe rate limits (though it might not need to)

you can run it as a Snippet or a Bookmarklet, see https://gabrielsroka.github.io/APIExplorer/

```javascript
javascript:
/* Bookmark name: /Delete Users# */
(async function () {
    var url = '/api/v1/users?filter=status eq "SUSPENDED"'; /* DEPROVISIONED, SUSPENDED, etc. */
    while (url) {
        const response = await fetch(url);
        const users = await response.json();
        for (const u of users) {
            console.log(u.profile.login, u.status);
            if (u.status != 'DEPROVISIONED') {
                await $.ajax(`/api/v1/users/${u.id}`, {method: 'delete'}); /* Must delete it twice. */
            }
            await $.ajax(`/api/v1/users/${u.id}`, {method: 'delete'});
        }
        url = getNextUrl(response);
    }
    console.log('done');

    function getNextUrl(response) {
        const links = {};
        response.headers.get('link').split(', ').forEach(link => {
            const [, url, name] = link.match(/<(.*)>; rel="(.*)"/);
            links[name] = url;
        });
        if (links.next) {
            const nextUrl = new URL(links.next); /* links.next is an absolute URL; we need a relative URL. */
            return nextUrl.pathname + nextUrl.search;
        }
    }
})();
```

**Comment by macf0x** [comment]
Just gave this a spin and it works great.

Had an exception on a user that was the technical contact, that was also suspended. Didn't want to remove it anyway. But is there a way to avoid that?

**Comment by gabrielsroka** [comment]
you might be able to add it to the `filter`, or check the user's login/id in the code. i don't think there's an api to tell you who the technical contact is (tho u might be able to scrape the html)

**Comment by gabrielsroka** [comment]
i was wrong. you can use `/api/v1/org/contacts/technical`. it returns the `userId` of the user

**Comment by gabrielsroka** [comment]
or, you can check for errors and recover gracefully

**Comment by macf0x** [comment]
Nice I'll give that a shot.

**Comment by gabrielsroka** [comment]
@macf0x i found this old thread while looking for something else. right after my last post, i started working a console: https://gabrielsroka.github.io/console for bits of code like this. i've rewritten the code above using the console. notice it's much shorter -- a lot of the fetch/pagination/rate-limit/etc. logic is in the console itself.

```js
// Delete users using https://gabrielsroka.github.io/console

if (!confirm('Delete Users?')) return;

url = '/api/v1/users?filter=status eq "SUSPENDED"'  // DEPROVISIONED, SUSPENDED, etc.

for await (user of getObjects(url)) {
  log('Deleting', user.profile.login, user.status)
  if (user.status != 'DEPROVISIONED') remove(`/api/v1/users/${user.id}`) // Must call delete twice.
  await remove(`/api/v1/users/${user.id}`)
}
log('Done.')
```

![image](https://user-images.githubusercontent.com/14354736/215901938-5efed8ad-e4be-4014-872a-cfdf5ff3d174.png)

**Comment by gabrielsroka** [comment]
There's example code for this in the console

**Comment by macf0x** [comment]
I'm guessing it's possible to evaluate EL (for group rules) without creating a group rule as the gui has a preview option.

I was more interested in the EL evaluation for attribute/profile mapping as there is no preview option for that.

If only we could see the Okta source, to see how there variant of SPEL works. :)

**Comment by gabrielsroka** [comment]
> there is no preview

There is a preview, and i have code for that private api, too.


```js
sourceExpression = `Arrays.flatten('HR,IT')`

body = {
     sourceId: 'oty4i04zqxXELIxKO0h7',
     targetId: 'oty4mlx8f1wOkt0f00h7',
     propertyMappings: [{
         targetField: 'salesforceGroups',
         sourceExpression
     }],
     userId: '00u4i04zqjEWyt4TW0h7'
 }
prev = await postJson('/api/internal/v1/mappings/preview?includeAllTargetFields=false', body)
log(sourceExpression, '=>', prev.propertyMappings[0].error || prev.propertyMappings[0].value)
```

**Comment by macf0x** [comment]
Yes you are correct. I was confused. The bit that doesn't have a preview is in the apps EL. 

ie. Login/username and group attributes, (under the OIDC/SAML apps).  The EL for OIDC claims can be previewed sort of, via the token preview, but you need to save. you can iterate through test conviently or quickly.

But this is awesome. Okta need to put you on the payroll :)

**Comment by gabrielsroka** [comment]
there are previews for that, too. 

or, for SAML, use a SAML tracer. rockstar has one built in.

**Comment by macf0x** [comment]
Is it really a preview if you need the save/change the config.
