### ISSUE TITLE
Feature request - add timestamp and user info to a report header

### ISSUE THREAD

**Issue by panchocarmano** [gabrielsroka/gabrielsroka.github.io#25]
I love this extension, but it would be helpful to me if there were a timestamp and userId of the logged in user who pulls the data. Is this something you may add to the Rockstar custom version?

**Comment by gabrielsroka** [comment]
Thanks for the kind works.

The timestamp is in the filename (of most [all ?] reports). Where would I put the username? in the csv? which reports?
