### ISSUE TITLE
Feature Request- Add Firefox support to Rockstar

### ISSUE THREAD

**Issue by NGatti1997** [gabrielsroka/gabrielsroka.github.io#27]

**Comment by gabrielsroka** [comment]
if you use the Greasemonkey extension for Firefox:
https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/

there's a userscript for rockstar that does most of what the Chrome extension does:
https://gabrielsroka.github.io/rockstar/rockstar.user.js

Firefox (and other browsers) are adopting Chrome's extension format, but last time i tried (a while ago), it didn't work. perhaps it's better now (or soon will be)

**Comment by gabrielsroka** [comment]
I haven't tried it on tampermonkey. Only on Greasemonkey.

**Comment by NGatti1997** [comment]
Seems to be an issue with how TamperMonkey handles CSP. Greasemonkey looks to workaround this issue.

**Comment by NGatti1997** [comment]
Going to reopen this because using Greasemonkey, I can't minimize or switch location of Rockstar overlay.

**Comment by gabrielsroka** [comment]
yep. i said it "does most of what the Chrome extension does"

btw, i just tried the Firefox extension again. it partially render, but then doesn't really work, and it doesn't show any errors. so, no luck there.

**Comment by gabrielsroka** [comment]
fixed: https://addons.mozilla.org/en-US/firefox/addon/rockstar-gabrielsroka/

thanks to the Backupta team for their help on this!
