### ISSUE TITLE
Show SSO doesn't work

### ISSUE THREAD

**Issue by steve-klein-Au** [gabrielsroka/gabrielsroka.github.io#30]
The Okta interface has changed, and the tiles we see are now square, not rectangular.

Click **Show SSO** pops up what looks like a search box, but the sso items under the tiles aren't visible, like they are in your Youtube demo.

All I see this:
![image](https://user-images.githubusercontent.com/73239985/169387741-6f50f0b5-98e2-4a76-a8f7-173185cefbb4.png)

**Comment by gabrielsroka** [comment]
Correct. It changed a long time ago. 

You can right click on a tile, copy the URL, paste it in to rockstar, then click Show SSO
