### ISSUE TITLE
'Verify Factors' for user does not show YubiKey (possibly other hardware tokens too)

### ISSUE THREAD

**Issue by gilesmarshall** [gabrielsroka/gabrielsroka.github.io#31]
Hi,
`/api/v1/users/me/factors` displays `factorType` as `token:hardware`
However, _Verify Factors_ from the Rockstar menu responds with `No supported factors were found.`

Also `webauthn` factorType is not displayed

Edit
I use this feature to check if a user has registered an MFA at all - but upon reflection, is this intended just to .. er.. Verify the factor?
In which case it would be useful to have the option to quickly display all registered factors when troubleshooting (without pulling the uid and using API explorer)

Thanks for a such as useful extension!
Giles

**Comment by gabrielsroka** [comment]
Verify factors is unable to verify WebAuthn. That's why it doesn't show up-it's unsupported. Perhaps the error message could be made clearer.

You can use More Actions > Reset Multifactor to show all enrolled factors.

**Comment by gabrielsroka** [comment]
You don't have to pull the UID when using API Explorer, it will do it for you.

> Thanks
You're welcome

**Comment by gilesmarshall** [comment]
Doh! Thanks for the reminder about More Actions - I've become so used to using Rockstar to check info about users.
And I didn't realise it dropped in the UID - brilliant!

Thanks for the prompt reply.
Happy to close
