### ISSUE TITLE
Show SSO and the new end user dashboard

### ISSUE THREAD

**Issue by mkoch7811** [gabrielsroka/gabrielsroka.github.io#33]
Hi Gabe! In the new end user dashboard, selecting Show SSO no longer places a button beneath each app to view the SAML assertion. Instead an SSO dialog appears, prompting for a URL. Not clear what URL to enter there. Just wondering if the previous functionality can be restored.

**Comment by gabrielsroka** [comment]
Hi Mike

i just posted on this 
https://github.com/gabrielsroka/gabrielsroka.github.io/issues/30
and on YouTube

Gabriel [not, Gabe, please]
