### ISSUE TITLE
App ID via label

### ISSUE THREAD

**Issue by DCrawfordNHS** [gabrielsroka/gabrielsroka.github.io#34]
Thankyou again for creating such a useful tool. Do you know if it is at all possible to get an Applications ID by searching on its label rather than its name:
{{url}}/api/v1/apps?filter=name+eq+%22ApplicationNameHere%22 successfully gets the name however
{{url}}/api/v1/apps?filter=label+eq+%22ApplicationLabelHere%22 does not retrieve the label

**Comment by gabrielsroka** [comment]
it doesn't look like it:
https://developer.okta.com/docs/reference/api/apps/#filters

but you can use `q` instead:
```
{{url}}/api/v1/apps?q=Label
```

**Comment by DCrawfordNHS** [comment]
Thats perfect, thankyou very much, your quick reply is extremely appreciated.

**Comment by DCrawfordNHS** [comment]
If my app is named Record and Learn from Patient Safety Incidents (UAT) is it possible to search for that given it uses brackets.

Kindest regards
Darren

Darren Crawford
Application Support Officer
Corporate IT & Smarter Working
Contact me on ***@***.***>

**Comment by gabrielsroka** [comment]
yes, but we call those parentheses in the US, not brackets. did you try it?

these questions are generic to the Okta API, and not specific to rockstar or my other tools.

i suggest using other resources for answers your questions, eg:
1. the Okta docs
2. Okta support pages and groups
3. community sites, for example, macadmins.slack.com

**Comment by DCrawfordNHS** [comment]
No probs, thanks for putting me on the right path
