### ISSUE TITLE
Not all Export Users columns are selectable unless "Manage applications" for admin role is checked

### ISSUE THREAD

**Issue by ctrang032** [gabrielsroka/gabrielsroka.github.io#36]
For custom admin roles, I can check every box except for Manage applications and Rockstar only shows half of the available user attributes to be exported. As soon as I enable Manage applications, this allows all columns to be selectable.
![image](https://user-images.githubusercontent.com/65986795/178634296-a5b39023-75a8-4c3d-b983-0680a993d00e.png)

My admin is able to view all user details, run API explorer to view all available attributes completely fine. However Export User columns are limited because their role does not have "Manage applications" available which I thought was odd.

There's nothing different about the user attributes, it includes custom/additional attributes from workday; it just looks like it gets cutoff.
full view
![image](https://user-images.githubusercontent.com/65986795/178632868-5753e372-498d-4b57-9f0a-bf442728b212.png)

limited view
![image](https://user-images.githubusercontent.com/65986795/178633716-0d734e26-5df1-4159-8f8c-0cc524a58ea8.png)

Is this by design? I find it weird that enabling "Manage applications" will allow the rest of the columns to be available.

**Comment by ctrang032** [comment]
a bit more detail, it gets cut off at attribute 44 out of 63

**Comment by gabrielsroka** [comment]
In order to call the API to see all the custom attributes, you need appropriate admin privs. This is not a bug, it's a limitation in the API.

**Comment by ctrang032** [comment]
Oh that's interesting. So enabling Manage applications grants a bit more privileges for rockstar to able to list more custom attributes for the export? 
Using API explorer, without Manage application, the admin is able to see all custom attributes, so it isn't an issue with the user viewing it, but moreso allowing rockstar to populate the available columns to be exported under Export Users?

**Comment by ctrang032** [comment]
Just checked Profile Editor, it is actually only custom attributes that are not listed to be available.

**Comment by ctrang032** [comment]
actually, thinking the logic through this, that makes sense. Since custom attributes are attributes of applications. Without managing capabilities of the app, rockstar does not have the ability to pull that info.
