### ISSUE TITLE
Add SAM Account Name as a column to export

### ISSUE THREAD

**Issue by sebastian-aaron** [gabrielsroka/gabrielsroka.github.io#37]
Hi,

Can we please add SAM Account Name as a column to export in okta/admin/users?

Appreciate you work for the community.

Thank you,
Sebastian

**Comment by gabrielsroka** [comment]
All custom columns should be there. You need to be a super admin in order to see them. That's an API limitation.

**Comment by sebastian-aaron** [comment]
Hi Gabriel,

Thank you for the prompt response.

I am a super admin on the platform. (this role has been assigned via group
not individual). Not sure if that makes any difference.

[image: image.png]
I can see the employee number but not SAM Account Name

Thank you,
Arun.

**Comment by gabrielsroka** [comment]
Was there supposed to be an image above? I don't see it. Is Sam account name in the user object?

**Comment by sebastian-aaron** [comment]
Hi Gabriel,

Sam Account name is a field within Additional Active Directory
Attributes, this is under user profile.
I have reattached the previous image. (image is from rockstar)

Thanks,
Arun.

**Comment by gabrielsroka** [comment]
There is no image. Can you paste it directly into GitHub?

You can only see attributes in the user profile, not in active directory.

**Comment by sebastian-aaron** [comment]
Hi Gabriel,

I dont think image is that helpful. It is just the columns to select from
rockstar.
I am only talking about the attributes within user profile.

And I have found one more thing this "Additional Active Directory
Attributes" section you will find only in Okta PROD environment. When I
checked my dev environment it is not there.

Do you have access to an OKta PROD environment?

Thanks,
Arun.

**Comment by gabrielsroka** [comment]
I don't really understand your problem and you're not helping me to understand it. Honestly, I don't think this is a rockstar issue. Please contact Okta support or check their documentation.

**Comment by gabrielsroka** [comment]
Yes. I wrote that in two different comments above. Please reread them.
