### ISSUE TITLE
Feature Request - Help Desk Push

### ISSUE THREAD

**Issue by takeittothemax** [gabrielsroka/gabrielsroka.github.io#38]
I saw that you are able to push a factor down to the end user. It would be nice to see if that user approved or denied the request. 

For instance, help desk is working with end user and when requesting sensitive information you could use this push/validate. This is a helpful validation for both the end user or help desk.

**Comment by gabrielsroka** [comment]
That's exactly how the feature works. Did you try it? There's also a video on my YouTube channel about it.

**Comment by takeittothemax** [comment]
Let me try it again. Might of been an issue with the dev account I was testing with.

**Comment by takeittothemax** [comment]
I apologize this worked on production account. Not sure why it isn't working with Dev account. Thank you
