### ISSUE TITLE
userType is blank on people export

### ISSUE THREAD

**Issue by TwoFifteen** [gabrielsroka/gabrielsroka.github.io#4]
When exporting users from Directory -> People, the userType field is empty.

To confirm it wasn't just an issue with userType, I also created a custom schema attribute named employeeType. This field is also blank on export.

These attributes are both populated on the user profile.
![image](https://user-images.githubusercontent.com/437288/78860272-a2439b00-79e6-11ea-88ca-d2e200fe8178.png)

In addition, when clicking "Show User" in rockstar, it does properly identify both userType and employeeType fields. However, as previously stated, both of these fields are blank on export.
![image](https://user-images.githubusercontent.com/437288/78860840-0b77de00-79e8-11ea-8edf-eb733d85dd02.png)

Export results confirming userType and employeeType are blank.
![image](https://user-images.githubusercontent.com/437288/78860688-a91edd80-79e7-11ea-83ff-54ce64956e90.png)

**Comment by gabrielsroka** [comment]
@TwoFifteen,

userType worked for me.

Is the user active? Did you use a query/filter/search on the export?

**Comment by TwoFifteen** [comment]
@gabrielsroka 

Very strange - Just tried it with the query/filter/search and it came out in the export. But if I clear the query/filter/search and just do the export it comes out blank.

![image](https://user-images.githubusercontent.com/437288/78863787-3fa2cd00-79ef-11ea-9a61-f82bcc2d21a5.png)

Export with query/filter/search
![image](https://user-images.githubusercontent.com/437288/78863824-547f6080-79ef-11ea-9d58-5788685b468c.png)

Export without query/filtersearch
![image](https://user-images.githubusercontent.com/437288/78863973-990afc00-79ef-11ea-97fb-deeddc35183a.png)

**Comment by gabrielsroka** [comment]
I'm guessing it's a bug in the API. I'll try to repro. Are you able to
verify? Either through rockstar or through Postman?

**Comment by gabrielsroka** [comment]
It worked for me without query/filter/search.

I also tried in rockstar using the API Explorer, and it worked:
![image](https://user-images.githubusercontent.com/14354736/78903175-9d570980-7a2f-11ea-99eb-04736ccb9d6a.png)

**Comment by TwoFifteen** [comment]
I think there must have been some type of delay between when I mass uploaded that field and when the API picked it up. I'm not sure but I just tried now and its working. I'll close this issue.
