### ISSUE TITLE
Feature Request: Menu collapsed by default

### ISSUE THREAD

**Issue by jboyle-ld** [gabrielsroka/gabrielsroka.github.io#47]
Would it be possible to collapse the Rockstar menu by default? I only use it about 5-10% of the time that I'm using Okta so I end up closing the Rockstar menu about 100 times a day (essentially every time I open a new Okta window, since it obscures a bunch of Okta's native menu items). I know I can disable the Chrome extension, but I like having it always at the ready.

**Comment by gabrielsroka** [comment]
yes. click the _

**Comment by gabrielsroka** [comment]
you can also move it to the right. exercise left to the reader

**Comment by jboyle-ld** [comment]
I meant it would be nice if the "-" button had a memory, so that if the page is refreshed, it would stay collapsed, but I hadn't tried right-justification, that is a much more convenient location for the menu if its always going to be expanded. Thanks for the tip!

**Comment by gabrielsroka** [comment]
it does have a memory. did you try it? it would be nice if you tried it...

**Comment by jboyle-ld** [comment]
Wow, as if by magic, now its persisting across refreshes (it hadn't been previously). Ignore me, apparently PEBCAK!
