### ISSUE TITLE
Unable to export users

### ISSUE THREAD

**Issue by galinski-n** [gabrielsroka/gabrielsroka.github.io#49]
I've tried a few times, but I get an error on line 1247 of rockstar.js. Screenshot attached. 
![image](https://user-images.githubusercontent.com/106274712/210890204-d48e7641-a0ee-4466-9099-31a9db23ecc9.png)

**Comment by gabrielsroka** [comment]
Roughly how many users are you trying to export?

If it's more than a couple hundred thousand, consider breaking it into smaller chunks.

See #46 for more info and tips

**Comment by galinski-n** [comment]
that makes sense. i have ~18m users i'm trying to export. if i break it into chucks using search by last name and a letter, it ends up being incredibly slow (i'm at ~6000 users so far and it's been 15min). any suggestions on how to speed that up?

**Comment by gabrielsroka** [comment]
Are you using `search` or `filter`? Can you paste your actual query?

In terms of performance, please contact Okta Support. Rockstar just calls the Okta APIs.

**Comment by galinski-n** [comment]
Search! and yes, search=profile.lastName gt "E" <-- tried a variety of different queries similar to this.

**Comment by gabrielsroka** [comment]
> gt

I wonder if you tried `lt "E"` If it would work better. I saw some interesting behavior in my tenant but it's on preview. I assume yours is in production.

I have example code in PowerShell and Python https://github.com/gabrielsroka

**Comment by gabrielsroka** [comment]
I would also recommend trying the other options in issue #46, including Firefox, notifying Okta Support, using the built-in user report, etc.

**Comment by gabrielsroka** [comment]
`filter`

> Supports only the equal eq operator from the standard Okta API filtering semantics, except in the case of the lastUpdated property. This property can also use the inequality operators (gt, ge, lt, and le).

https://developer.okta.com/docs/reference/api/users/#list-users-with-a-filter

Maybe filter is faster than search.

**Comment by gabrielsroka** [comment]
Another thought. If you're going to run your own code, consider adding these `omit...` headers if you don't need the extra fields. It should improve performance:

https://developer.okta.com/docs/reference/api/users/#content-type-header-fields-2

**Comment by galinski-n** [comment]
thanks for all the helpful suggestions! i was able to successfully get all my users exported. and going forward, it should be much quicker as i will only be grabbing users with an oktaid greater than what i have.

**Comment by gabrielsroka** [comment]
I'm glad it worked. Do you mind sharing which tips were most helpful? Did you write your own code?

**Comment by galinski-n** [comment]
Of course! I ended up doing a mix of both. I exported all Suspended Users using rockstar (and a filter). But then I did the rest of the users (since it starts with Staged and then Active) in a simple Python script (grab all users, but stop once status = suspended). In addition, filter was much quicker than search when I was looking for specific things (and I'll keep that in mind for the future).

**Comment by gabrielsroka** [comment]
Thanks for that. If you don't mind sharing your Python code, that would be really helpful. Of course remove any URLs and API tokens and anything sensitive.

**Comment by gabrielsroka** [comment]
If you don't mind sharing your Python code, that would be really helpful. Of course remove any URLs and API tokens and anything sensitive.

**Comment by gabrielsroka** [comment]
this should be fixed by https://github.com/gabrielsroka/gabrielsroka.github.io/pull/57

i just submitted it to Google Chrome Store for approval

thanks again to @stashev
