### ISSUE TITLE
Request: Allow export of user's groups

### ISSUE THREAD

**Issue by PabloValarezo** [gabrielsroka/gabrielsroka.github.io#5]
Request: From a user's profile page -> Groups -> allow exporting a .csv list of all groups the user is assigned to.

It'd be great if the list included the source of the group (Okta, AD, G Suite, etc.)

**Comment by gabrielsroka** [comment]
Hi @PabloValarezo 

This is a feature to Export Group Memberships. 

The Okta API doesn't say whether it comes from AD or G Suite, etc. The only indication it gives is the logo, eg, 
https://op1static.oktacdn.com/assets/img/logos/groups/okta-medium.d7fb831bc4e7e1a5d8bd35dfaf405d9e.png
https://op1static.oktacdn.com/assets/img/logos/groups/office365-medium.7b7e50f8abb1398a914d9407fcf37f9a.png

i could parse that out and show "okta" or "office365", but i'm concerned it wouln't be very reliable

**Comment by PabloValarezo** [comment]
Understood. Is making calls back to the API to get the origin from the Group object itself possible?
`i.e. "type": "OKTA_GROUP"` [link](https://developer.okta.com/docs/reference/api/groups/#group-object)

**Comment by gabrielsroka** [comment]
i'm not sure what you mean. the export already contains the `type` attribute.

is that what you meant?

**Comment by PabloValarezo** [comment]
Ah, yes, I forgot it shows up as `APP_GROUP` instead of the app itself.

**Comment by gabrielsroka** [comment]
I'm going to close this. Please re-open it if you need to.
