### ISSUE TITLE
Missing properties in 'Export Group Members' for Admins with permission 'View users and their details'

### ISSUE THREAD

**Issue by trgrt** [gabrielsroka/gabrielsroka.github.io#50]
Hi,
First of all, BIG fan of your work! I can't tell you how much time it has saved me and my colleagues - as I'm sure everyone lets you know :)

Regardless - Just got a feedback from a user about a quirk in 'Export Group Members (custom)', where not all profile properties were exportable. I just verified for myself and found the following:

_This takes place on a groups page in EU, https://**#orgName#**-admin.okta-emea.com/admin/group/${groupId}_

When opening 'Export Group Members (custom)' as a super admin, all profile attributes are selectable for export, as expected

When opening 'Export Group Members (custom)' as a _custom_ admin with only the permission 'View users and their details' (for all users) only the _Base_ User Attributes are selectable for export. None of the _Custom_ user attributes from the Okta Profile

The same user on the same page observes the following though 'API Explorer':
 _GET/api/v1/users/${userId}_ recieves All user attributes for the specified user, both _Base_ & _Custom_. 
_GET/api/v1/meta/schemas/user/default_ recieves all available user attributes, , both _Base_ & _Custom_. 

Just thought I'd let you know, if _available attributes_ for the 'Export Group Members (custom)' functionality are fetched from some place where only super admins have permissions

**Comment by gabrielsroka** [comment]
this is a known issue. it's a "bug" (or missing feature) in Okta's API. u can't call it unless u have Super Admin (or enough privs).

it's been reported before (in the wrong repo): https://github.com/oktadev/rockstar/issues/6

**Comment by gabrielsroka** [comment]
Thank you for the kind words.

**Comment by trgrt** [comment]
Oh, got it! That's too bad from Oktas end. Sorry for the double post and thank you for the additional information! We'll find a suitable workaround and log a feature request to Okta instead

Of course! :)
Take care and all the best
