### ISSUE TITLE
feature request - Task error list

### ISSUE THREAD

**Issue by kpikamlesh** [gabrielsroka/gabrielsroka.github.io#53]
I noticed product is capable of web screen scraping.  Is it possible to spit our a list of all task errors?

**Comment by gabrielsroka** [comment]
although there is some code to screen scrape, i'm not maintaing it nor adding new ones.

you can use the browser DevTools to see which APIs it calls.

**Comment by kpikamlesh** [comment]
Thank you for getting back to me. Take care KamleshOn Mar 24, 2023, at 1:00 PM, Gabriel Sroka ***@***.***> wrote:﻿
although there is some code to screen scrape, i'm not maintaing it nor adding new ones.
you can use the browser DevTools to see which APIs it calls.
