### ISSUE TITLE
Map existing application and group in okta

### ISSUE THREAD

**Issue by srirao28** [gabrielsroka/gabrielsroka.github.io#55]
Experts,

Trying to map application & group

applicationID - abcd
groupID - xyzg
group name - admins

appId_groupId.csv - contents
applicationID,groupID,group
abcd,xyzg,admins

Import-Module OktaAPI
Connect-Okta "xyzabc" "https://abcXYZ_okta.com/"
function Add-AppAssign() {
$users = Import-Csv appId_groupId.csv
	foreach ($line in $lines) {
		Add-OktaAppGroup $line.applicationId $line.groupId $line.group
	}
}Add-AppAssign appId_groupId.csv
Error:
Invoke-RestMethod: {"errorCode":"E0000003","errorSummary":"The request body was not well-formed."

Inputs appreciated !

**Comment by gabrielsroka** [comment]
duplicate of https://github.com/gabrielsroka/OktaAPI.psm1/issues/29

please keep powershell issues in that repo. and open new issues, don't reuse old issues.
