### ISSUE TITLE
Feature request: add device count to Devices page

### ISSUE THREAD

**Issue by securitygeneration** [gabrielsroka/gabrielsroka.github.io#56]
It's mildly infuriating that the Devices page (https://company.okta.com/admin/devices-inventory) does not show a count of the devices displayed in the current view (taking into account filters). Could Rockstar do this locally?

**Comment by gabrielsroka** [comment]
usually those counts are generated by APIs (sometimes, private APIs). i don't think there's an API for device count.

you could export them and count them locally. or write a script to do it, but it would have to paginate, etc.
