### ISSUE TITLE
Request - load the plugin in minimized mode until i click on it

### ISSUE THREAD

**Issue by MCnunzio** [gabrielsroka/gabrielsroka.github.io#61]
I don't always use the plugin everytime i visit an okta page, which is very often. I would like the plugin to have an option to either always run in minimized mode until i click it, or better yet not open at all unless i click the extension icon. Currently, I'm resorting to disabling the plugin entirely until i need it and I would rather not have to

**Comment by gabrielsroka** [comment]
click the `_`

it's covered in the video

![image](https://github.com/gabrielsroka/gabrielsroka.github.io/assets/14354736/bc4c5005-c393-4e64-bfea-9786ff49cf78)
