### ISSUE TITLE
Ability to hide profile fields

### ISSUE THREAD

**Issue by syoung-quizlet** [gabrielsroka/gabrielsroka.github.io#7]
Thank you so much for writing this extension.  It's been a life saver.  A frustrating part of using Okta is all the extraneous fields when you are viewing a profile.  It would be great if we could hide the ones we aren't using.  This would help with getting the correct fields populated and reducing errors by entering information into incorrect fields.

**Comment by gabrielsroka** [comment]
Hi @syoung-quizlet 

I'm not sure which screen you're talking about. If you'd like to submit a PR, I can take a look.

Thanks.

**Comment by syoung-quizlet** [comment]
Apologies.  The Okta user profile screen.  With Okta they have a number of fields you can't hide.  By hiding the ones you don't use it makes entering profile information easier and ensures you have everything entered that is required.

*Sean Young*
IT Manager @ Quizlet

**Comment by gabrielsroka** [comment]
Hi Sean

Thanks for the clarification. I don't have anything like this in rockstar today, and it would be a fair amount of work, so I don't have any plans to add it.

As I wrote above, if you're interested in making the changes yourself (or hiring someone to do it), I'd consider a Pull Request.

Thanks.

**Comment by syoung-quizlet** [comment]
Thanks i'll see if someone can help me do it.  Appreciate the follow up and we are grateful for this extension!

*Sean Young*
IT Manager @ Quizlet
