### ISSUE TITLE
Unable to close out of rockstar interface on Admin Dashboard.

### ISSUE THREAD

**Issue by steakboy** [gabrielsroka/gabrielsroka.github.io#72]
Last week i noticed that I was unable to close out of the rockstar interface on the okta admin dashboard (https://domain-admin.okta.com/admin/dashboard). I have attempted to uninstall the extension, reinstall. try on a different computer. Same experience.
![image](https://github.com/user-attachments/assets/934ab650-75b3-4488-a89d-98f0d7c56026)

I can close out of the pop up interface on any other page within the Okta Admin dashboard (groups, people, applications, etc). But on this home page it wont close. Which blocks the hamburger menu to access everything else

**Comment by gabrielsroka** [comment]
> Can you move it to the right hand side? I think we found a bug a few days
ago but maybe causing it to crash. I'll take a look when I get back to the
office. Also, check the browser console for errors

**Comment by steakboy** [comment]
Lol, i never knew there was a "switch to other side" button. But yes, I can switch it to the other side to make Okta useable.

The console has no errors until I attempt to click the X, in which case it then errors:

DASHBOARD:163
Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'unsafe-inline' 'nonce-uz4lJV6c353rrJSzUUyBVw' 'unsafe-eval' 'self' mydomain.okta.com *.oktacdn.com blob:". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

My work is a Google Workspace org, so im using rockstar on a managed google chrome browser. Could this be a unique issue to me, and my orgs security settings? I run the infoSec team and cant think of any chrome updates weve made that line up with this error.

**Comment by gabrielsroka** [comment]
lol, i just repro'd. it's a CSP issue that only happens on certain screens. i'll see if i can fix it.

thanks for reporting it.

**Comment by gabrielsroka** [comment]
ok. i fixed it.  i'll publish it in a minute and it'll take Google a bit to roll it out.

thanks again.

**Comment by gabrielsroka** [comment]
i just got the update from Google. it seems to be fixed.

i'll close it now. if it comes back or you find something else, reopen it, or open a new one.

thanks. again.
