### ISSUE TITLE
Example for console docs

### ISSUE THREAD

**Issue by jwomackgsa** [gabrielsroka/gabrielsroka.github.io#76]
Hi, I just found the console app the other day and wanted to say thanks for developing it.  I wanted to share an example for you to maybe add to your examples doc on what was useful for me.  I had a situation where I need to run group assignment conversions on about 50 apps.  I was able to use console to do this in a programmatic fashion versus clicking in the UI over 50 times.  I think it could be useful for other.   The assignment conversion isn't published but I just debugged the website to see what calls where being made to replicate it and console worked perfectly for this.  Console makes working with the api in a quick fashion where before I would have to spin up a golang or powershell script to get things done.

```js
const itemsToExclude = ["app1", "service_app", "contoso.com"];  //Exclude app labels, AD, or ldap you don't want
for await (app of getObjects('/api/v1/apps')) {
  if (!itemsToExclude.some(item => app.label.includes(item))) {
   log(app.id + " - " + app.label) 
   url = '/api/v1/appAssignments/instance/' + app.id + '/async/convertAll'   
body = {
    jobId: null,
    complete: false,
    status: "",
    convertedCount: 0,
    scannedCount: 0
}
    response = await postJson(url, body);
    while (!response.complete) {
      await sleep(5000)
      response = await getJson(url);
      log(app.label + ' - ' + response.status)
}
  }
  if (cancel) break
}
log("Done")
```

**Comment by gabrielsroka** [comment]
Hi Jason, thanks for the kind words and sharing. i made a few minor changes.

is this using a private API?

```js
itemsToExclude = ['app1', 'service_app', 'contoso.com']  // Exclude app labels, AD, or ldap you don't want
for await (app of getObjects('/api/v1/apps')) {
  if (!itemsToExclude.some(item => app.label.includes(item))) {
    log(app.id, app.label) 
    url = '/api/v1/appAssignments/instance/' + app.id + '/async/convertAll'   
    body = {
      jobId: null,
      complete: false,
      status: '',
      convertedCount: 0,
      scannedCount: 0
    }
    convert = await postJson(url, body)
    while (!convert.complete) {
      await sleep(2000)
      convert = await getJson(url)
      log(app.label, convert.status)
    }
  }
  if (cancel) break
}
log('Done')
```

**Comment by jwomackgsa** [comment]
I will be honest I don't know the difference between private / public, but I just know it works against the admin url of the org that console is using when logged into the admin port (i.e https://{org}-admin.okta.com.  I didn't try it against a preview org so can say if that work.

**Comment by gabrielsroka** [comment]
i couldn't find the `appAssignments` endpoint on https://developer.okta.com so i assume it's a private/non-published API

**Comment by jwomackgsa** [comment]
Yes definitely unpublished but its not on the /internal/ api path that some are.
