### ISSUE TITLE
Export App Group feature is not exporting a custom attribute name "Profile URL" 

### ISSUE THREAD

**Issue by skibidi-rizler69** [gabrielsroka/gabrielsroka.github.io#77]
Hi All, new okta admin here 👋🏽
rockstar has a feature which allow okta admins to "Export App Groups" This export all the attributes accept some custom ones such as "Profile URL". It has few drop down values that is assigned to Salesforce app in our okta instance. 
Another attributes that are not exported are "Flow User" and "Service Cloud User" which are either set to true or false.
Other than that, extension works and helped me save bunch of time
<img width="682" alt="Screenshot 2024-11-08 at 5 24 23 PM" src="https://github.com/user-attachments/assets/68dcc667-be71-472c-b344-964c96bd30f7">
<img width="577" alt="image" src="https://github.com/user-attachments/assets/31ebb4f0-8ad4-4302-9112-98672f28e79c">
Let me know if more info is needed!

**Comment by gabrielsroka** [comment]
i'd recommend using my console https://gabrielsroka.github.io/console/ and something like https://github.com/gabrielsroka/gabrielsroka.github.io/blob/master/console/examples.md#export-apps-and-groups-to-csv
