### ISSUE TITLE
Feature Request - Add ability to export API Tokens and data into csv

### ISSUE THREAD

**Issue by disavow3133t** [gabrielsroka/gabrielsroka.github.io#79]
The Okta API currently does not support pulling a list of all active tokens (understandably for security purposes). We would like the ability to use this extension to pull the list of Active API Tokens as well any additional info from the token details and export them into a csv.

**Comment by gabrielsroka** [comment]
actually, i think it does. did you check the docs?

also, if it doesn't, i generally don't scrape the html or call the private api

**Comment by gabrielsroka** [comment]
https://developer.okta.com/docs/api/openapi/okta-management/management/tag/ApiToken/

**Comment by disavow3133t** [comment]
> https://developer.okta.com/docs/api/openapi/okta-management/management/tag/ApiToken/

Right, so I am aware of this and we are currently utilizing this in conjunction with a list of token id's we are pulling from the gui manually. Since it only works when knowing the Token ID. I was looking for another way to accomplish this but it seems that may not be possible at this time. Thanks for the quick response!

**Comment by gabrielsroka** [comment]
it lists all tokens

**Comment by disavow3133t** [comment]
> it lists all tokens

It seems there was a mixup in how we were trying to use our script to list the tokens which was causing an error compared to the documentation. I have since fixed it and it's working now! Thanks!
