### ISSUE TITLE
Can't seem to export app groups with more than 20 groups

### ISSUE THREAD

**Issue by Sai0777** [gabrielsroka/gabrielsroka.github.io#9]
Running into an issue with exporting groups tied to an app.  Any app with 20 or less app assignments seems to export just fine, but anything over 20 and the export hangs.  Is this expected or a limitation?

Thanks!

**Comment by gabrielsroka** [comment]
hi @Sai0777 

can you provide some of your code or steps? Is this with PowerShell or rockstar?

**Comment by Sai0777** [comment]
Hey @gabrielsroka ,

This is direct with rockstar.  https://imgur.com/a/M45ubV3  This is about a 30 second gif with what I'm seeing.  One app with 57 groups just sits, then another group with exactly 20 groups exports fine.  I did get these groups eventually querying the groups API via rockstar and noticed after 20 groups I essentially had to click to go to a second page of results.  I think the automatic export isn't able to "go" to that next page.

**Comment by gabrielsroka** [comment]
hi @Sai0777 

thanks for the update. i was able to repro. the fix should be easy. i'll work on it asap and let you know when it's published on the Chrome store.

the Okta API paginates after 20 groups. the "first" page is working, but i need to fix the "second" and subsequent pages.

by the way, the Chrome Dev Console (press F12 on Windows) showed additional info -- in case you run into issues in the future, this is a good place to look

**Comment by Sai0777** [comment]
@gabrielsroka Awesome, thank you!  If I run into any other issues I'll be sure to check out the Dev Console for more details.  :)

**Comment by gabrielsroka** [comment]
ok. i just submitted v 0.11. It might take a few minutes or a few hours, for Google to review and publish it.

**Comment by Sai0777** [comment]
@gabrielsroka Looking good and working now!  Thank you!

**Comment by gabrielsroka** [comment]
@Sai0777 
Great. I'll close this for now. If there's any other issue, let me know.

Thank you for reporting this bug and for using rockstar!
